### ISSUE TITLE
AlignReads ERROR

### ISSUE THREAD

**Issue by Siyue-888** [MD-Anderson-Bioinformatics/SpliceSeq#15]
Hi,

I'm runnning SpliceSeq（Windows） locally with an aim to process my own RNA-seq data. I have set up a comparison between two samples just to check its working but I keep getting 'AlignReads ERROR' and the error message is as follows:

2024-12-13 10:36:13,389 [main] INFO - Sequence align databae does not exist.  Creating SeqDB\\H_sapiens.GraphSeqDB.299.20140108
2024-12-13 10:36:13,448 [main] INFO - Generating Sequence Database for 19036 splicegraphs
2024-12-13 11:36:42,428 [main] INFO - Generated 1000 of 19036
2024-12-13 16:05:07,863 [main] INFO - Generated 2000 of 19036
2024-12-13 16:38:49,124 [main] INFO - Generated 3000 of 19036
2024-12-13 17:17:30,315 [main] INFO - Generated 4000 of 19036
2024-12-13 18:02:57,765 [main] INFO - Generated 5000 of 19036
2024-12-13 18:59:27,987 [main] INFO - Generated 6000 of 19036
2024-12-13 20:22:23,622 [main] INFO - Generated 7000 of 19036
2024-12-13 22:42:40,455 [main] INFO - Generated 8000 of 19036
2024-12-14 09:28:55,232 [main] ERROR - Error saving splice graph: SELECT species, symbol, chr, strand, start, stop from graph where graph_id = '8040'
com.mysql.jdbc.CommunicationsException: Communications link failure due to underlying exception: 

** BEGIN NESTED EXCEPTION ** 

java.net.SocketException
MESSAGE: Software caused connection abort: recv failed

STACKTRACE:

java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:113)
	at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:160)
	at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:188)
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:1931)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2380)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1600)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1695)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3020)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:2949)
	at com.mysql.jdbc.Statement.executeQuery(Statement.java:959)
	at splicetool.common.util.DB.getSpliceGraph(DB.java:1566)
	at splicetool.analyze.util.SeqDBGen.generateSeqDB(SeqDBGen.java:257)
	at splicetool.analyze.ImportReads.createAlignSeqDB(ImportReads.java:116)
	at splicetool.analyze.ImportReads.main(ImportReads.java:615)

** END NESTED EXCEPTION **

Last packet sent to the server was 48 ms ago.
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2592)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1600)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1695)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3020)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:2949)
	at com.mysql.jdbc.Statement.executeQuery(Statement.java:959)
	at splicetool.common.util.DB.getSpliceGraph(DB.java:1566)
	at splicetool.analyze.util.SeqDBGen.generateSeqDB(SeqDBGen.java:257)
	at splicetool.analyze.ImportReads.createAlignSeqDB(ImportReads.java:116)
	at splicetool.analyze.ImportReads.main(ImportReads.java:615)
2024-12-14 09:28:55,232 [main] ERROR - Error generating sequence database: 
com.mysql.jdbc.CommunicationsException: Communications link failure due to underlying exception: 

** BEGIN NESTED EXCEPTION ** 

java.net.SocketException
MESSAGE: Software caused connection abort: recv failed

STACKTRACE:

java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:113)
	at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:160)
	at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:188)
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:1931)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2380)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1600)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1695)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3020)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:2949)
	at com.mysql.jdbc.Statement.executeQuery(Statement.java:959)
	at splicetool.common.util.DB.getSpliceGraph(DB.java:1566)
	at splicetool.analyze.util.SeqDBGen.generateSeqDB(SeqDBGen.java:257)
	at splicetool.analyze.ImportReads.createAlignSeqDB(ImportReads.java:116)
	at splicetool.analyze.ImportReads.main(ImportReads.java:615)

** END NESTED EXCEPTION **

Last packet sent to the server was 48 ms ago.
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:2592)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1600)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1695)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3020)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:2949)
	at com.mysql.jdbc.Statement.executeQuery(Statement.java:959)
	at splicetool.common.util.DB.getSpliceGraph(DB.java:1566)
	at splicetool.analyze.util.SeqDBGen.generateSeqDB(SeqDBGen.java:257)
	at splicetool.analyze.ImportReads.createAlignSeqDB(ImportReads.java:116)
	at splicetool.analyze.ImportReads.main(ImportReads.java:615)

Additionally, I have another issue which is that each step of the process takes about 1 hour. Is this normal?

Kind Regards,

Siyue

**Comment by ChrisWakefield** [comment]
Hello Siyue,
Thanks for your message and sorry that you ran into trouble using spliceseq.  And that it took so long for me to reply.

This problem sounds like it's related to configuration, database connections, or understanding the tool’s workflow.  Please:
(A) Refer to https://bioinformatics.mdanderson.org/public-software/spliceseq/installation/ for instructions to set up a database for use, and
(B) Note the paragraph stating "The default SpliceSeq DB is also no longer accessible online. You can change a configuration setting to open other SpliceSeq DBs or use your own SpliceSeq DB on your local machine." 

Regarding the time required, the process of alignment is described on page https://bioinformatics.mdanderson.org/public-software/spliceseq/dataloading/.  You may have to refer to documentation for Bowtie to see if there are ways to speed the tasks.

I hope this helps.  Please post here if you have further questions or more to add.

Regards,
Chris
