### ISSUE TITLE
AlignReads ERROR

### ISSUE THREAD

**Issue by sallymurray** [MD-Anderson-Bioinformatics/SpliceSeq#6]
Hi,

I'm runnning SpliceSeq locally with an aim to process my own RNA-seq data. I have set up a comparison between two samples just to check its working but I keep getting 'AlignReads ERROR'. 

I have downloaded Bowtie version 1 as recommended and checked the set up against the website instructions, but I can't seem to fix this.

Kind Regards,

Sally

**Comment by mryaninsilico** [comment]
Sally,

 

Can you send me the log files?  If the bowtie program is not in your path, you will need to edit the SGAnalyzer.properties file or settings panel in the gui for BowtieExe and BowtieDBBuildExe to include the full path of where it is installed.  Like /usr/mike/Bowtie/bin  or C:\\user\\mike\\bowtie\\bin.  Also you need the original bowtie version 1.something not the bowtie 2.

 

Mike

**Comment by sallymurray** [comment]
Hi Mike,

These are my most recent couple of runs. 

/Users/mms/Desktop/SpliceSeq
15:18:50 WARN - Could not delete from group_comparision Table 'splicegraph.group_comparison' doesn't exist
15:18:50 WARN - Could not delete from comparision Table 'splicegraph.comparison' doesn't exist
15:18:50 INFO - 04/22/20 15:18:50 Job: STUDY.TEST2 Step: 1 InsertStudy RUNNING

15:18:51 INFO - 04/22/20 15:18:51 Job: STUDY.TEST2 Step: 1 InsertStudy COMPLETE

15:18:51 INFO - 04/22/20 15:18:51 Job: SAMPLE.1 Step: 1 AlignReads RUNNING

15:18:52 INFO - 04/22/20 15:18:52 Job: SAMPLE.1 Step: 1 AlignReads ERROR

/Users/mms/Desktop/SpliceSeq
15:18:59 INFO - 04/22/20 15:18:59 Job: STUDY.TEST2 Step: 1 InsertStudy PREVIOUSLY_COMPLETED

15:18:59 INFO - 04/22/20 15:18:59 Job: SAMPLE.1 Step: 1 AlignReads RUNNING

15:19:00 INFO - 04/22/20 15:19:00 Job: SAMPLE.1 Step: 1 AlignReads ERROR

I did make sure to download the right version of Bowtie (version 1 for macOS) and I used the paths listed on the info panel from both the bowtie and bowtie-build exe files.

Thanks,

Sally

**Comment by mryaninsilico** [comment]
In your SpliceSeq install directory, there should be a log4j.xml file.  If not, there is one attached.  Put it in the directory where the SpliceSeq .jar files are installed.

 

In the log4j.xml file, we need to turn up the logging level.  Change the line:

 

<priority value="info"/>

 

To

 

<priority value="debug"/>

**Comment by sallymurray** [comment]
Hi Mike,

I have tried this and it is returning the following on sys 'insert study complete' but alignment just remains at running. It states 'AnalysisController failed to start processing. Semaphore file not found'. There is also no information on the stat or log tab, i'm not sure if this is normal.

I'm new to this so there is every chance I have messed up an installation somewhere, but if you could point me in the right direction, I'd be very grateful!

Kind Regards,

Sally

**Comment by mryaninsilico** [comment]
Sally,

 

I think the original issue is that the path to bowtie is not quite right.  By putting in the debugging flag, we should be able to see the command line that it is trying to run and we could figure out what is wrong.  It would also let us run the bowtie command line outside of SpliceSeq to make sure everything is OK and if not there might be a more helpful error message.  Not sure what is happening now with the Semaphore file message.  I would try a machine restart or uninstall / reinstall of SpliceSeq.

 

Can you tell me a bit more about how you are running?  What type of computer are you using (Mac/PC/Linux) and are you running from the SpliceSeq GUI or using the command line and a study definition file for the analysis?  Finally, what type of study are you doing?  How many RNASeq sample files do you have and are you comparing groups of samples to find splicing differences?

 

I am working on a Docker version of the software which should be much easier to run because all of the setup / configuration will be pre done.  I should have that in a few days to try.  Might work better for you.

 

Mike

**Comment by sallymurray** [comment]
Hi Mike,

I'm working on a Mac with the GUI. I was hoping to compare two groups of paired end sample, the condition with 11 samples and the control with 41. This is probably more than my computer can handle so I may have to knock it back considerably!

Thanks so much for your help,

Sally

**Comment by sallymurray** [comment]
Hi Mike,

I got everything up and running on my laptop (windows this time) using the GUI but there is a further error I am running into:
2020-05-04 10:28:16,907 [main] DEBUG - Bowtie Executable = C:\Users\sally\OneDrive\Desktop\bowtie-1.0.0\bowtie.exe
2020-05-04 10:28:16,908 [main] DEBUG - Bowtie Parameters = --best --strata -k 20 -v 2 -m 19
2020-05-04 10:28:16,908 [main] DEBUG - Bowtie Database Path = C:\Users\sally\OneDrive\Desktop\SpliceTool\build\SeqDB
2020-05-04 10:28:16,908 [main] DEBUG - Default search provider is Bowtie
2020-05-04 10:28:17,026 [main] INFO - Sequence align databae does not exist.  Creating C:\Users\sally\OneDrive\Desktop\SpliceTool\build\SeqDB\\H_sapiens.GraphSeqDB.199.20140108
2020-05-04 10:28:17,043 [main] DEBUG -   Got DB.getConnection() jdbc:mysql://localhost splicegraph
2020-05-04 10:28:17,125 [main] INFO - Generating Sequence Database for 19036 splicegraphs
2020-05-04 10:30:06,354 [main] INFO - Generated 1000 of 19036
2020-05-04 10:34:30,955 [main] INFO - Generated 2000 of 19036
2020-05-04 10:36:00,428 [main] INFO - Generated 3000 of 19036
2020-05-04 10:36:43,868 [main] INFO - Generated 4000 of 19036
2020-05-04 10:37:53,617 [main] INFO - Generated 5000 of 19036
2020-05-04 10:41:00,963 [main] INFO - Generated 6000 of 19036
2020-05-04 10:42:45,406 [main] INFO - Generated 7000 of 19036
2020-05-04 10:43:29,324 [main] INFO - Generated 8000 of 19036
2020-05-04 10:44:53,623 [main] INFO - Generated 9000 of 19036
2020-05-04 10:46:38,009 [main] INFO - Generated 10000 of 19036
2020-05-04 10:48:02,477 [main] INFO - Generated 11000 of 19036
2020-05-04 10:48:46,207 [main] INFO - Generated 12000 of 19036
2020-05-04 10:49:47,166 [main] INFO - Generated 13000 of 19036
2020-05-04 10:50:26,893 [main] INFO - Generated 14000 of 19036
2020-05-04 10:51:58,707 [main] INFO - Generated 15000 of 19036
2020-05-04 10:53:19,574 [main] INFO - Generated 16000 of 19036
2020-05-04 10:54:57,439 [main] INFO - Generated 17000 of 19036
2020-05-04 10:56:07,832 [main] INFO - Generated 18000 of 19036
2020-05-04 10:56:35,668 [main] INFO - Generated 19000 of 19036
2020-05-04 10:56:36,266 [main] DEBUG -   DB.releaseConnection()
2020-05-04 10:56:36,266 [main] INFO - Building Bowtie database: C:\Users\sally\OneDrive\Desktop\SpliceTool\build\SeqDB\\H_sapiens.GraphSeqDB.199.20140108
2020-05-04 10:56:36,267 [main] DEBUG -    Command line= C:\Users\sally\OneDrive\Desktop\bowtie-1.0.0\bowtie-build.exe -q -f C:\Users\sally\OneDrive\Desktop\SpliceTool\build\SeqDB\\H_sapiens.GraphSeqDB.199.20140108.fa C:\Users\sally\OneDrive\Desktop\SpliceTool\build\SeqDB\\H_sapiens.GraphSeqDB.199.20140108
2020-05-04 11:01:09,525 [main] INFO -   Completed bowtie DB build.
2020-05-04 11:01:09,526 [main] INFO - Exon sequence databae created.
2020-05-04 11:01:09,550 [main] INFO - Aligining reads to exon sequences for SRR84
2020-05-04 11:01:09,558 [main] DEBUG - Performing align of reads to splice graphs with Bowtie - paired ends
2020-05-04 11:01:09,558 [main] DEBUG - Running Bowtie
2020-05-04 11:01:09,560 [main] DEBUG - Command line=C:\Users\sally\OneDrive\Desktop\bowtie-1.0.0\bowtie.exe --best --strata -k 20 -v 2 -m 19 --un C:\Users\sally\OneDrive\Documents\FASTAS\CTRL\SRR957884_1.fastq.unaligned C:\Users\sally\OneDrive\Desktop\SpliceTool\build\SeqDB\\H_sapiens.GraphSeqDB.199.20140108 C:\Users\sally\OneDrive\Documents\FASTAS\CTRL\SRR957884_1.fastq,C:\Users\sally\OneDrive\Documents\FASTAS\CTRL\SRR957884_2.fastq C:\Users\sally\OneDrive\Desktop\SpliceTool\Temp\SRR957884_1.fastq.rslt
2020-05-04 12:22:09,016 [main] ERROR -      Error while flushing and closing output
2020-05-04 12:22:14,481 [main] ERROR -      terminate called after throwing an instance of 'int'
2020-05-04 12:22:14,506 [main] ERROR - Bowtie did not run correctly: 
2020-05-04 12:22:14,506 [main] ERROR - Command line=C:\Users\sally\OneDrive\Desktop\bowtie-1.0.0\bowtie.exe --best --strata -k 20 -v 2 -m 19 --un C:\Users\sally\OneDrive\Documents\FASTAS\CTRL\SRR957884_1.fastq.unaligned C:\Users\sally\OneDrive\Desktop\SpliceTool\build\SeqDB\\H_sapiens.GraphSeqDB.199.20140108 C:\Users\sally\OneDrive\Documents\FASTAS\CTRL\SRR957884_1.fastq,C:\Users\sally\OneDrive\Documents\FASTAS\CTRL\SRR957884_2.fastq C:\Users\sally\OneDrive\Desktop\SpliceTool\Temp\SRR957884_1.fastq.rslt
2020-05-04 12:22:14,506 [main] DEBUG - Complted: align of reads to splice graphs with Bowtie
2020-05-04 12:22:14,522 [main] ERROR - Error aligning reads to splice graphs. 
java.lang.NullPointerException
	at splicetool.analyze.ImportReads.alignReads(ImportReads.java:182)
	at splicetool.analyze.ImportReads.main(ImportReads.java:627)

Is this something you have encountered before?

Kind Regards,

Sally

**Comment by mryaninsilico** [comment]
Hi Sally.  That looks like good progress.  The error that caused the later issue is: 

 

 

2020-05-04 11:01:09,560 [main] DEBUG - Command line=C:\Users\sally\OneDrive\Desktop\bowtie-1.0.0\bowtie.exe --best --strata -k 20 -v 2 -m 19 --un C:\Users\sally\OneDrive\Documents\FASTAS\CTRL\SRR957884_1.fastq.unaligned C:\Users\sally\OneDrive\Desktop\SpliceTool\build\SeqDB\H_sapiens.GraphSeqDB.199.20140108 C:\Users\sally\OneDrive\Documents\FASTAS\CTRL\SRR957884_1.fastq,C:\Users\sally\OneDrive\Documents\FASTAS\CTRL\SRR957884_2.fastq C:\Users\sally\OneDrive\Desktop\SpliceTool\Temp\SRR957884_1.fastq.rslt
2020-05-04 12:22:09,016 [main] ERROR - Error while flushing and closing output



It looks like this came from bowtie and is most often caused by running out of disk space on your computer.  Is it possible that the computer was out of space on the hard drive toward the end of this alignment?

 

If so, is it possible for you to get a portable drive?  Like a USB drive like this one https://www.amazon.com/Western-Digital-Elements-Portable-External/dp/B06VVS7S94/ref=sr_1_2?dchild=1 <https://www.amazon.com/Western-Digital-Elements-Portable-External/dp/B06VVS7S94/ref=sr_1_2?dchild=1&qid=1588598969&refinements=p_n_feature_two_browse-bin%3A5446812011&s=pc&sr=1-2> &qid=1588598969&refinements=p_n_feature_two_browse-bin%3A5446812011&s=pc&sr=1-2.  If you moved all of your RNASeq sample .fastq files to a portable drive, it would leave a lot of space on your laptop for the analysis files as SpliceSeq / bowtie runs.

 

Mike

**Comment by sallymurray** [comment]
Hi Mike,

Thankyou for the advice, I have followed your recommendation and managed to complete a job fully just comparing two samples. The only problem is the debug mode reported the following:

2020-05-06 01:51:01,583 [main] DEBUG -      # reads processed: 7495863
2020-05-06 01:51:01,583 [main] DEBUG -      # reads with at least one reported alignment: 31072 (0.41%)
2020-05-06 01:51:01,583 [main] DEBUG -      # reads that failed to align: 7451166 (99.40%)
2020-05-06 01:51:01,583 [main] DEBUG -      # reads with alignments suppressed due to -m: 13625 (0.18%)
2020-05-06 01:51:01,583 [main] DEBUG -      Reported 136451 alignments to 1 output stream(s)

Admittedly I did use trimmomatic adjust minlen and cut phred score below 20 prior to uploading the fastas.

Is this the issue?

I really appreciate the help you have given me with this, this is a last minute Masters project!

Kind Regards,

Sally

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mryaninsilico** [comment]
The alignment is terrible so there is definitely a problem.  Is your data poly(A) enriched RNASeq data?  What is the length of your reads and what did you set read length to in spliceseq?

**Comment by sallymurray** [comment]
Hi Mike,

It is poly(A) RNA-seq data. I am using a publicly available data set but they were very clear that base pair reads were 101bp in length. I tried this alignment again with the RAW data and got 74-77% alignment.

Am I right in thinking I can adjust the parameters from the BowtieParms? I read somewhere that I can further improve the alignment by adjusting the insert size. In the original analysis of this data, they used a phred score cut off of 30 so I was hoping to do the same.

Can I ask you if you have a recommended cut off sample size per group? Each sample results is around 30million reads and I was hoping to compare a group of 41 samples to a group of 11.

Kind Regards,

Sally

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by mryaninsilico** [comment]
Hi,

 

70+% alignment is good.  Only complete protein coding transcripts are included in our transcript models so pseudogenes and non-coding poly(A) transcripts will not align.

 

You can set bowtie parameters.  There is a file in your spliceseq install - SGAnalyzer.properties.  In there you will find a line: BowtieParms=--best --strata -k 20 -v 2 -m 19.  You can set any supported bowtie parms here.  For example if your computer has multiple cores and you use the –p option (like –p 3) the alignments will run faster. You may also be able to do this through a GUI panel.  

 

The way that SpliceSeq performs its alignments, the insert size filtering will not be relevant.  You can read the bowtie documentation on the –v and –n alignment options to see if one works for you on quality filtering.  By default we rely on the –v option to control max mismatches (entire read) so that we don’t get errant splice counts from a read with many mismatches at the end of a read that just crosses into the next exon by a few bases.  The –v option ignores quality scores though.  You could experiment with the –n method but you will need to be careful about how it is set / the types of alignments accepted.  Also, I believe the software needs bowtie run with the –best option.

 

I think the comparison of 41 to 11 samples will work.  Let me know if there are issues.  After the comparison completes, it might be good to touch base on filtering that helps to identify the most robust splice events.

 

Mike

**Comment by sallymurray** [comment]
Hi Mike,

I completed a full run of all the samples with no hitches using the raw reads. The alignments in bowtie ranged between 58 – 80%. As a standard, for the data uploaded to TCGA spliceseq, were raw reads used or was data trimmed beforehand?

Also, I was wondering which set of transcripts and genome version is used for this program?

Kind Regards,

Sally

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
