### ISSUE TITLE
spliceseq can't connect to mysql

### ISSUE THREAD

**Issue by mhjiang97** [MD-Anderson-Bioinformatics/SpliceSeq#9]
Hi,

I’d like to use SpliceSeq to quantify splicing events in my RNA-seq data. But SpliceSeq can’t connect to MySQL after configuring it.

Settings are:
```
DBURL              jdbc:mysql://localhost
SGDatabase         splicegraph
DBUser             mjiang
DBPassword         mjiang
```
I'm sure that I can log in mysql through `mysql -u mjiang -p -h localhost` and there's a database named `splicegraph`
```
$mysql -u mjiang -p -h localhost
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 88
Server version: 8.0.23 MySQL Community Server - GPL

Copyright (c) 2000, 2021, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use splicegraph;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
+--------------------------+
| Tables_in_splicegraph    |
+--------------------------+
| attribute                |
| exon                     |
| graph                    |
| graph_ncbi_annotation    |
| graph_uniprot_annotation |
| graph_uniprot_map        |
| isoform                  |
| isoform_ex_seq           |
| protein_feature_ref      |
| splice                   |
| uniprot_exon_align       |
| uniprot_feature_ref      |
| uniprot_prot_seq         |
| version                  |
+--------------------------+
14 rows in set (0.00 sec)

mysql>
```
Could you give me some advice about configuring SpliceSeq or mysql?
Thanks in advance.

**Comment by mryaninsilico** [comment]
Hi.  Did you download the 2.3 version: http://projects.insilico.us.com/SpliceSeq_2.3/SpliceSeq.zip?

 

Also, could you look in the SpliceSeq directory to see if any file with a .log extension has an error message.

 

Michael Ryan, PhD

In Silico Solutions 

 

From: Minghao Jiang ***@***.*** 
Sent: Tuesday, April 13, 2021 3:44 AM
To: MD-Anderson-Bioinformatics/SpliceSeq
Cc: Subscribed
Subject: [MD-Anderson-Bioinformatics/SpliceSeq] spliceseq can't connect to mysql (#9)

 

Hi,

I’d like to use SpliceSeq to quantify splicing events in my RNA-seq data. But SpliceSeq can’t connect to MySQL after configuring it.

Settings are:

DBURL              jdbc:mysql://localhost
 
SGDatabase         splicegraph
 
DBUser             mjiang
 
DBPassword         mjiang
 

I'm sure that I can log in mysql through mysql -u mjiang -p -h localhost and there's a database named splicegraph

$mysql -u mjiang -p -h localhost
 
Enter password:
 
Welcome to the MySQL monitor.  Commands end with ; or \g.
 
Your MySQL connection id is 88
 
Server version: 8.0.23 MySQL Community Server - GPL
 
 
 
Copyright (c) 2000, 2021, Oracle and/or its affiliates.
 
 
 
Oracle is a registered trademark of Oracle Corporation and/or its
 
affiliates. Other names may be trademarks of their respective
 
owners.
 
 
 
Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
 
 
 
mysql> use splicegraph;
 
Reading table information for completion of table and column names
 
You can turn off this feature to get a quicker startup with -A
 
 
 
Database changed
 
mysql> show tables;
 
+--------------------------+
 
| Tables_in_splicegraph    |
 
+--------------------------+
 
| attribute                |
 
| exon                     |
 
| graph                    |
 
| graph_ncbi_annotation    |
 
| graph_uniprot_annotation |
 
| graph_uniprot_map        |
 
| isoform                  |
 
| isoform_ex_seq           |
 
| protein_feature_ref      |
 
| splice                   |
 
| uniprot_exon_align       |
 
| uniprot_feature_ref      |
 
| uniprot_prot_seq         |
 
| version                  |
 
+--------------------------+
 
14 rows in set (0.00 sec)
 
 
 
mysql>
 

Could you give me some advice about configuring SpliceSeq or mysql?
Thanks in advance.

**Comment by mhjiang97** [comment]
Hi,
I ran `SpliceSeq version 2.3` then configured it, and the log file read:
```
2021-04-14 10:13:42,068 [AWT-EventQueue-0] INFO - Application name set to SpliceSeq in configuration
2021-04-14 10:13:42,069 [AWT-EventQueue-0] INFO - Retrieving application path from environment variable SPLICESEQ_HOME
2021-04-14 10:13:42,069 [AWT-EventQueue-0] WARN - SPLICESEQ_HOME was not read from the environment, assuming relative path
2021-04-14 10:13:42,071 [AWT-EventQueue-0] INFO - Retrieving application path from environment variable SPLICESEQ_HOME
2021-04-14 10:13:42,071 [AWT-EventQueue-0] WARN - SPLICESEQ_HOME was not read from the environment, assuming relative path
2021-04-14 10:13:42,072 [AWT-EventQueue-0] INFO - Retrieving application path from environment variable SPLICESEQ_HOME
2021-04-14 10:13:42,072 [AWT-EventQueue-0] WARN - SPLICESEQ_HOME was not read from the environment, assuming relative path
2021-04-14 10:13:42,072 [AWT-EventQueue-0] INFO - Retrieving application path from environment variable SPLICESEQ_HOME
2021-04-14 10:13:42,072 [AWT-EventQueue-0] WARN - SPLICESEQ_HOME was not read from the environment, assuming relative path
2021-04-14 10:13:42,075 [AWT-EventQueue-0] INFO - Retrieving application path from environment variable SPLICESEQ_HOME
2021-04-14 10:13:42,075 [AWT-EventQueue-0] WARN - SPLICESEQ_HOME was not read from the environment, assuming relative path
2021-04-14 10:14:12,902 [AWT-EventQueue-0] ERROR - java.sql.SQLException: The url does not correspond with any known host: please check Ratway url.
2021-04-14 10:14:12,915 [AWT-EventQueue-0] ERROR - java.sql.SQLException: The url does not correspond with any known host: please check Ratway url.
2021-04-14 10:14:12,917 [AWT-EventQueue-0] ERROR - java.sql.SQLException: The url does not correspond with any known host: please check Ratway url.
2021-04-14 10:14:12,938 [AWT-EventQueue-0] ERROR - java.sql.SQLException: The url does not correspond with any known host: please check Ratway url.
2021-04-14 10:15:02,956 [AWT-EventQueue-0] ERROR - Error loading samples: java.sql.SQLException: The url does not correspond with any known host: please check Ratway url.
2021-04-14 10:15:16,105 [AWT-EventQueue-0] ERROR - java.sql.SQLException: Cannot communicate with the Ratway webapp: please check if the url is correct.
2021-04-14 10:15:19,884 [AWT-EventQueue-0] ERROR - Error loading samples: java.sql.SQLException: Cannot communicate with the Ratway webapp: please check if the url is correct.
2021-04-14 10:15:27,650 [AWT-EventQueue-0] ERROR - java.sql.SQLException: Cannot communicate with the Ratway webapp: please check if the url is correct.
2021-04-14 10:17:03,659 [AWT-EventQueue-0] INFO - Retrieving application path from environment variable SPLICESEQ_HOME
2021-04-14 10:17:03,659 [AWT-EventQueue-0] WARN - SPLICESEQ_HOME was not read from the environment, assuming relative path
2021-04-14 10:17:03,660 [AWT-EventQueue-0] INFO - Retrieving application path from environment variable SPLICESEQ_HOME
2021-04-14 10:17:03,660 [AWT-EventQueue-0] WARN - SPLICESEQ_HOME was not read from the environment, assuming relative path
2021-04-14 10:17:03,661 [AWT-EventQueue-0] INFO - Retrieving application path from environment variable SPLICESEQ_HOME
2021-04-14 10:17:03,661 [AWT-EventQueue-0] WARN - SPLICESEQ_HOME was not read from the environment, assuming relative path
2021-04-14 10:17:03,662 [AWT-EventQueue-0] INFO - Retrieving application path from environment variable SPLICESEQ_HOME
2021-04-14 10:17:03,662 [AWT-EventQueue-0] WARN - SPLICESEQ_HOME was not read from the environment, assuming relative path
2021-04-14 10:17:03,662 [AWT-EventQueue-0] INFO - Retrieving application path from environment variable SPLICESEQ_HOME
2021-04-14 10:17:03,662 [AWT-EventQueue-0] WARN - SPLICESEQ_HOME was not read from the environment, assuming relative path
2021-04-14 10:17:04,295 [AWT-EventQueue-0] ERROR - java.sql.SQLException: Cannot communicate with the Ratway webapp: please check if the url is correct.
2021-04-14 10:17:04,956 [AWT-EventQueue-0] ERROR - java.sql.SQLException: Cannot communicate with the Ratway webapp: please check if the url is correct.
2021-04-14 10:17:05,110 [AWT-EventQueue-0] ERROR -   Failed to create DB Connection
2021-04-14 10:17:05,110 [AWT-EventQueue-0] ERROR - java.lang.NullPointerException
2021-04-14 10:17:09,357 [AWT-EventQueue-0] ERROR - Error loading samples: java.lang.NullPointerException
2021-04-14 10:17:09,370 [AWT-EventQueue-0] ERROR -   Failed to create DB Connection
2021-04-14 10:17:09,371 [AWT-EventQueue-0] ERROR - java.lang.NullPointerException
2021-04-14 10:17:22,716 [AWT-EventQueue-0] INFO - Retrieving application path from environment variable SPLICESEQ_HOME
2021-04-14 10:17:22,716 [AWT-EventQueue-0] WARN - SPLICESEQ_HOME was not read from the environment, assuming relative path
2021-04-14 10:17:22,717 [AWT-EventQueue-0] INFO - Retrieving application path from environment variable SPLICESEQ_HOME
2021-04-14 10:17:22,717 [AWT-EventQueue-0] WARN - SPLICESEQ_HOME was not read from the environment, assuming relative path
2021-04-14 10:17:22,718 [AWT-EventQueue-0] INFO - Retrieving application path from environment variable SPLICESEQ_HOME
2021-04-14 10:17:22,718 [AWT-EventQueue-0] WARN - SPLICESEQ_HOME was not read from the environment, assuming relative path
2021-04-14 10:17:22,718 [AWT-EventQueue-0] INFO - Retrieving application path from environment variable SPLICESEQ_HOME
2021-04-14 10:17:22,719 [AWT-EventQueue-0] WARN - SPLICESEQ_HOME was not read from the environment, assuming relative path
2021-04-14 10:17:22,719 [AWT-EventQueue-0] INFO - Retrieving application path from environment variable SPLICESEQ_HOME
2021-04-14 10:17:22,719 [AWT-EventQueue-0] WARN - SPLICESEQ_HOME was not read from the environment, assuming relative path
2021-04-14 10:17:22,721 [AWT-EventQueue-0] ERROR -   Failed to create DB Connection
2021-04-14 10:17:22,721 [AWT-EventQueue-0] ERROR - java.lang.NullPointerException
2021-04-14 10:17:22,723 [AWT-EventQueue-0] ERROR -   Failed to create DB Connection
2021-04-14 10:17:22,723 [AWT-EventQueue-0] ERROR - java.lang.NullPointerException
2021-04-14 10:17:24,571 [AWT-EventQueue-0] INFO - Retrieving application path from environment variable SPLICESEQ_HOME
2021-04-14 10:17:24,571 [AWT-EventQueue-0] WARN - SPLICESEQ_HOME was not read from the environment, assuming relative path
2021-04-14 10:17:24,572 [AWT-EventQueue-0] INFO - Retrieving application path from environment variable SPLICESEQ_HOME
2021-04-14 10:17:24,572 [AWT-EventQueue-0] WARN - SPLICESEQ_HOME was not read from the environment, assuming relative path
2021-04-14 10:17:24,573 [AWT-EventQueue-0] INFO - Retrieving application path from environment variable SPLICESEQ_HOME
2021-04-14 10:17:24,573 [AWT-EventQueue-0] WARN - SPLICESEQ_HOME was not read from the environment, assuming relative path
2021-04-14 10:17:24,574 [AWT-EventQueue-0] INFO - Retrieving application path from environment variable SPLICESEQ_HOME
2021-04-14 10:17:24,574 [AWT-EventQueue-0] WARN - SPLICESEQ_HOME was not read from the environment, assuming relative path
2021-04-14 10:17:24,574 [AWT-EventQueue-0] INFO - Retrieving application path from environment variable SPLICESEQ_HOME
2021-04-14 10:17:24,575 [AWT-EventQueue-0] WARN - SPLICESEQ_HOME was not read from the environment, assuming relative path
2021-04-14 10:17:24,576 [AWT-EventQueue-0] ERROR -   Failed to create DB Connection
2021-04-14 10:17:24,576 [AWT-EventQueue-0] ERROR - java.lang.NullPointerException
2021-04-14 10:17:24,578 [AWT-EventQueue-0] ERROR -   Failed to create DB Connection
2021-04-14 10:17:24,578 [AWT-EventQueue-0] ERROR - java.lang.NullPointerException
```

**Comment by mryaninsilico** [comment]
How are you starting the SpliceSeq viewer?  When DB connection fails, there should be a program stack trace in the window where you started spliceseq.  Can you get a screen shot of the stack trace?  For example if running on windows in a command prompt window by typing java –jar spliceseq.jar, then see what messages are printed in the window.  On a mac it is a terminal window I think.

 

Like this:



 

Mike

**Comment by mhjiang97** [comment]
I typed `java -jar SpliceSeq.jar` on my Mac, and configured it.

I'm sorry that i don't know how to attach pictures in the github,
and the screenshot of the stack trace was:
```
** BEGIN NESTED EXCEPTION **

java.io.EOFException

STACKTRACE:

java.io.EOFException
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:1934)
	at com.mysql.jdbc.MysqlIO.readPacket(MysqlIO.java:483)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:992)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2572)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1485)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:233)
	at splicetool.common.util.DB.getConnection(DB.java:4104)
	at splicetool.common.util.DB.connectionValid(DB.java:49)
	at splicetool.viewer.Application.run(Application.java:254)
	at splicetool.viewer.Main.createAndShowGUI(Main.java:124)
	at splicetool.viewer.Main.access$000(Main.java:27)
	at splicetool.viewer.Main$1.run(Main.java:158)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)


** END NESTED EXCEPTION **




Last packet sent to the server was 1 ms ago.
	at com.mysql.jdbc.MysqlIO.readPacket(MysqlIO.java:554)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:992)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2572)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1485)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:233)
	at splicetool.common.util.DB.getConnection(DB.java:4104)
	at splicetool.common.util.DB.connectionValid(DB.java:49)
	at splicetool.viewer.Application.changeViewType(Application.java:468)
	at splicetool.viewer.Application.run(Application.java:286)
	at splicetool.viewer.Main.createAndShowGUI(Main.java:124)
	at splicetool.viewer.Main.access$000(Main.java:27)
	at splicetool.viewer.Main$1.run(Main.java:158)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
2021-04-15 10:47:28,061 [AWT-EventQueue-0] ERROR -   Failed to create DB Connection
2021-04-15 10:47:28,061 [AWT-EventQueue-0] ERROR - java.lang.NullPointerException
```

**Comment by mryaninsilico** [comment]
I have not seen this problem before.  It is not a user id or password problem.  I did find a similar issue with a solution reported in the link below.  Could you try that please and let me know if it works.

 

https://forums.mysql.com/read.php?39,52805,273371

 

Mike

**Comment by mhjiang97** [comment]
Hi, I'm here again.
I added `mysqld : ALL : ALLOW` into `/etc/hosts`

Now, the error from SpliceSeq is:
```
java.sql.SQLException: Unknown initial character set index '255' received from server. Initial client character set can be forced via the 'characterEncoding' property.
	at com.mysql.jdbc.Connection.configureClientCharacterSet(Connection.java:2268)
	at com.mysql.jdbc.Connection.initializePropsFromServer(Connection.java:3748)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2585)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1485)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:233)
	at splicetool.common.util.DB.getConnection(DB.java:4104)
	at splicetool.common.util.DB.connectionValid(DB.java:49)
	at splicetool.viewer.Application.run(Application.java:254)
	at splicetool.viewer.Main.createAndShowGUI(Main.java:124)
	at splicetool.viewer.Main.access$000(Main.java:27)
	at splicetool.viewer.Main$1.run(Main.java:158)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
2021-04-20 15:13:22,005 [AWT-EventQueue-0] ERROR -   Failed to create DB Connection
2021-04-20 15:13:22,005 [AWT-EventQueue-0] ERROR - java.lang.NullPointerException
```
Thank you for your patience!
